src/Entity/Commentary.php
<?php

namespace App\Entity;

use App\Repository\CommentaryRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentaryRepository::class)]
class Commentary
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_publication = null;

    #[ORM\ManyToOne(inversedBy: 'commentaries')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    #[ORM\ManyToOne(inversedBy: 'commentaries')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Article $article = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getDatePublication(): ?\DateTimeInterface
    {
        return $this->date_publication;
    }

    public function setDatePublication(\DateTimeInterface $date_publication): static
    {
        $this->date_publication = $date_publication;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): static
    {
        $this->article = $article;

        return $this;
    }
}

src/Form/CommentaryType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\User;
use App\Entity\Commentary;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentaryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('content')
            ->add('date_publication')
            ->add('author', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'name',
                ])
            ->add('article', EntityType::class, [
                'class' => Article::class,
                'choice_label' => 'title', 
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commentary::class,
        ]);
    }
}

src/Controller/CommentaryController.php
<?php

namespace App\Controller;

use App\Entity\Commentary;
use App\Form\CommentaryType;
use App\Repository\CommentaryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/commentary')]
class CommentaryController extends AbstractController
{
    #[Route('/', name: 'app_commentary_index', methods: ['GET'])]
    public function index(CommentaryRepository $commentaryRepository): Response
    {
        return $this->render('commentary/index.html.twig', [
            'commentaries' => $commentaryRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_commentary_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $commentary = new Commentary();
        $form = $this->createForm(CommentaryType::class, $commentary);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($commentary);
            $entityManager->flush();

            return $this->redirectToRoute('app_commentary_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('commentary/new.html.twig', [
            'commentary' => $commentary,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commentary_show', methods: ['GET'])]
    public function show(Commentary $commentary): Response
    {
        return $this->render('commentary/show.html.twig', [
            'commentary' => $commentary,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_commentary_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Commentary $commentary, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CommentaryType::class, $commentary);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_commentary_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('commentary/edit.html.twig', [
            'commentary' => $commentary,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commentary_delete', methods: ['POST'])]
    public function delete(Request $request, Commentary $commentary, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commentary->getId(), $request->request->get('_token'))) {
            $entityManager->remove($commentary);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_commentary_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/commentary/_delete_form.html.twig
<form method="post" action="{{ path('app_commentary_delete', {'id': commentary.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commentary.id) }}">
    <button class="btn">Delete</button>
</form>

templates/commentary/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/commentary/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commentary{% endblock %}

{% block body %}
    <h1>Edit Commentary</h1>

    {{ include('commentary/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_commentary_index') }}">back to list</a>

    {{ include('commentary/_delete_form.html.twig') }}
{% endblock %}

templates/commentary/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentary index{% endblock %}

{% block body %}
    <h1>Commentary index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Content</th>
                <th>Date_publication</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commentary in commentaries %}
            <tr>
                <td>{{ commentary.id }}</td>
                <td>{{ commentary.content }}</td>
                <td>{{ commentary.datePublication ? commentary.datePublication|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_commentary_show', {'id': commentary.id}) }}">show</a>
                    <a href="{{ path('app_commentary_edit', {'id': commentary.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_commentary_new') }}">Create new</a>
{% endblock %}

templates/commentary/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commentary{% endblock %}

{% block body %}
    <h1>Create new Commentary</h1>

    {{ include('commentary/_form.html.twig') }}

    <a href="{{ path('app_commentary_index') }}">back to list</a>
{% endblock %}

templates/commentary/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentary{% endblock %}

{% block body %}
    <h1>Commentary</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commentary.id }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ commentary.content }}</td>
            </tr>
            <tr>
                <th>Date_publication</th>
                <td>{{ commentary.datePublication ? commentary.datePublication|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_commentary_index') }}">back to list</a>

    <a href="{{ path('app_commentary_edit', {'id': commentary.id}) }}">edit</a>

    {{ include('commentary/_delete_form.html.twig') }}
{% endblock %}